name: Deploy repository to Github Pages

on:
  push:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Build Index
      run: |
        chmod +x build_site.sh
        # Builds the index into _site/master/index.yml
        ./build_site.sh _site/master

    - name: Setup Node and PNPM
      uses: pnpm/action-setup@v4
      with:
        package_json_file: site_generator/package.json

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: latest

    - name: Generate html index page
      run: |
        cd site_generator
        npm i -g ts-node
        pnpm install --frozen-lockfile
        npm run ci-build
        # Copy generated HTML to the root of the deployment
        cp -r site/* ../_site/

    - name: Upload Pages Artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: '_site'
    
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}master/index.yml
    runs-on: ubuntu-24.04
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
